version: 0.2.{build}
branches:
  only:
  - dev
image:
- Visual Studio 2019
configuration:
- Release
platform: x64
clone_folder: Serenity/build
build_script:
- cmd: >-
    mkdir build
    cmake -G %generator% -D CMAKE_BUILD_TYPE=%build_type%
    cmake -B build --config %build_type% -S .