version: 0.2.{build}
branches:
  only:
  - dev
image:
- Visual Studio 2019
configuration:
- Release
platform: x64
build_script:
- cmd: >-
    mkdir build

    cmake -G "Visual Studio 16 2019" -A x64 -D CMAKE_BUILD_TYPE=Release

    cmake -B build --config Release -S .