version: 0.2.{build}
branches:
  only:
  - dev
image:
- Visual Studio 2019
configuration:
- Release
platform: x64
clone_folder: Serenity/build
environment:
  matrix:
  - generator: '"Visual Studio 16 2019" -A x64'
  - build_type: RELEASE
build_script:
- cmd: >-
   mkdir build

   cd build
   
   cmake -G %generator% -DCMAKE_BUILD_TYPE=%build_type% ../
