version: 0.2.{build}
branches:
  only:
  - dev
image:
- Visual Studio 2019
clone_folder: Serenity/build
environment:
  matrix:
  - generator: '"Visual Studio 16 2019" -A x64'
  - build_type: Release
build_script:
- cmd: >-
   mkdir build

   cd build
   
   cmake --build . --config %build_type% -G %generator% -D CMAKE_BUILD_TYPE=%build_type% ..
