version: 0.2.{build}
branches:
  only:
  - main
  - dev
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    BUILD_DIR: "build2019"
    GENERATOR: '"Visual Studio 16 2019" -A x64'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    BUILD_DIR: "build2022"
    GENERATOR: '"Visual Studio 17 2022" -A x64'


build_script:
- cmd: >-
    mkdir %BUILD_DIR%

    cmake -B %BUILD_DIR%  -G %GENERATOR% -D CMAKE_BUILD_TYPE=Release -S .
