version: 0.2.{build}
branches:
  only:
  - dev
image:
- Visual Studio 2019
configuration:
- Release
platform: x64
build_script:
- cmd: >-
    mkdir build2019

    cmake -B build2019  -G "Visual Studio 16 2019" -A x64 -D CMAKE_BUILD_TYPE=Release -S .

    mkdir build2022

    cmake -B build2022  -G "Visual Studio 17 2022" -A x64 -D CMAKE_BUILD_TYPE=Release -S .
