#####################################################################################################################
# Removed Sandbox and Build All CI builds as the Sandbox is really only used by me to experiment testing with 
# features and implementations while the Build All case is redundant since we test each option separately.
# - In total this removed 12 tests bringing the current build tests to 24 (added 3 missing for VS16 Demos).
# - The reason for so many builds is:
#   * Three tests for each sub project to test the formatting backend support (ArgFormatter, fmtlib, and <format>)
#   * The sub projects being Serenity only, Serenity W/ Demos, Serenity W/ Tests, and Serenity W/ Benchmarks
#   * Two variations of the above: one for Visual Studio 16 and one for Visual Studio 17
#####################################################################################################################
version: 1.0.0.{build}
branches:
  only:
  - main
  - dev
environment:
  matrix:
################################################################################
#  Library only Builds for native, fmtlib, and <format> for VS16
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library W/ Tests builds for native, fmtlib, and <format> for VS16
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'  
################################################################################

################################################################################
#  Library W/Demos Builds for native, fmtlib, and <format> for VS16
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library W/ Benchmark Builds for native, fmtlib, and <format> for VS16
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: '"Visual Studio 16 2019" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library only builds for native, fmtlib, and <format> For VS 17
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library W/Demos Builds for native, fmtlib, and <format> for VS17
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'ON'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library W/Tests Builds for native, fmtlib, and <format>
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'ON'
    BUILD_BENCHMARKS: 'OFF'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

################################################################################
#  Library W/Benchmark Builds for native, fmtlib, and <format>
################################################################################
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'ON'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'ON'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'ON'
    USE_FMTLIB: 'OFF'
    DISABLE_NATIVE_WARNING: 'OFF'

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    GENERATOR: '"Visual Studio 17 2022" -A x64'
    BUILD_SANDBOX: 'OFF'
    BUILD_DEMOS: 'OFF'
    BUILD_TESTS: 'OFF'
    BUILD_BENCHMARKS: 'ON'
    BUILD_ALL : 'OFF'
    USE_NATIVEFMT: 'OFF'
    USE_STDFMT: 'OFF'
    USE_FMTLIB: 'ON'
    DISABLE_NATIVE_WARNING: 'OFF'
################################################################################

build_script:
- cmd: >-
    mkdir build

    cmake -B build -G %GENERATOR% -D BUILD_SANDBOX=%BUILD_SANDBOX% -D BUILD_DEMOS=%BUILD_DEMOS% -D BUILD_TESTS=%BUILD_TESTS% -D BUILD_BENCHMARKS=%BUILD_BENCHMARKS% -D BUILD_ALL=%BUILD_ALL% -D USE_NATIVEFMT=%USE_NATIVEFMT% -D USE_FMTLIB=%USE_FMTLIB% -D USE_STDFMT=%USE_STDFMT% -D DISABLE_NATIVE_WARNING=%DISABLE_NATIVE_WARNING% -S .

    cmake --build build --config=Release
