serenity::expiremental::targets::FileTarget Class Reference
This class is in charge of logging to any basic file type and inherits from the TargetBase class for common logging functions and logging settings.
#include <FileTarget.h>
Public Member Functions
FileTarget ()
Default constructor that sets the logger name to `File_Target` and sets all other values to their defaults.
 FileTarget (std::string_view fileName, bool replaceIfExists=false)
Constructor that will set the file name and will truncate the file if it already exists and if `replaceIfExists` is set to true. Sets all other values to their defaults.
 FileTarget (std::string_view name, std::string_view filePath, bool replaceIfExists=false)
Constructor that will set the logger name, file path, log directory, and whether or not to truncate this file if it exists or not. Sets all other values to their defaults.
 FileTarget (std::string_view name, std::string_view formatPattern, std::string_view filePath, bool replaceIfExists=false)
Constructor that will set the logger name, format pattern to use, file path, log directory, and whether or not to truncate this file if it exists or not. Sets all other values to their defaults.
FileTarget (const FileTarget &)=delete
Deleted.
 FileTarget & operator= (const FileTarget &)=delete
Deleted.
 ~FileTarget ()
Cleans up any background threads, flushes contents to disk, and closes the file context being used.
const std::string FilePath ()
Returns the file path of the file context currently being held.
const std::string FileName ()
Returns the file name of the file context currently being held.
void EraseContents ()
Closes the file context currently being held and re-opens the same file context, truncating the file size to 0.
virtual bool RenameFile (std::string_view newFileName)
Closes the file (if open) and trys to rename current file context. If rename is succesful, will re-open file context under the new file name.
bool OpenFile (bool truncate=false)
Opens the file held by the file handle.
bool CloseFile ()
Joins any currently running flush background thread (if enabled) and if the file handle's file context is currently open, will flush contents to disk and close the file.
void Flush ()
If contents were written to buffer, this will now write contents of buffer to file and flush contents to disk, otherwise, just flushes contents to disk.
Protected Member Functions
void PolicyFlushOn () override
Executes the currently set flush policy.
void PrintMessage (std::string_view formatted) override
Writes the message passed in by the formatted variable to the file context.
Protected Attributes
std::ofstream fileHandle
 FileSettings fileOptions
 BackgroundThread flushWorker
Detailed Description
This class is in charge of logging to any basic file type and inherits from the TargetBase class for common logging functions and logging settings.
For all FileTarget Constructors:
If either the directories or the file don't exist yet, the constructor will create the neccessary
 directories as well as the file needed to write to.
Default initializes the TargetBase inherited values
These being the flush policy, the log level, and time mode.
For the constructors that don't take in a format pattern, this also includes the default pattern
 For the constructors that don't take a file path argument:
The log directory and log itself is created in the location that the application being run is located.
The default log directory is named `Logs`.
The default file name is `Generic_Log.txt` and will be created under the default log directory.
Constructor & Destructor Documentation
FileTarget() [1/3]
serenity::expiremental::targets::FileTarget::FileTarget (std::string_view fileName, bool replaceIfExists = false) [explicit]
Constructor that will set the file name and will truncate the file if it already exists and if `replaceIfExists` is set to true. Sets all other values to their defaults.
While the file name will be changed to the parameter fileName, the file itself will be created under the default log directory.
Parameters
fileName The name of the file to create and/or use for logging
replaceIfExist This value denotes whether or not to truncate the file if it exists already
FileTarget() [2/3]
serenity::expiremental::targets::FileTarget::FileTarget (std::string_view name, std::string_view filePath, bool replaceIfExists = false) [explicit]
Constructor that will set the logger name, file path, log directory, and whether or not to truncate this file if it exists or not. Sets all other values to their defaults.
The name of the logger will be set based on the name variable. The file path should include the log directory and the actual file name in the filePath variable as this is how it's intended to be parsed. If the file already exists and the replaceIFExists variable is set to true, then the file will be truncated before opening for use in logging
Parameters
name The name the logger will be identified by.
filePath the full path to the file. This value should include any directories as well as the file name itself.
replaceIfExist This value denotes whether or not to truncate the file if it exists already
FileTarget() [3/3]
serenity::expiremental::targets::FileTarget::FileTarget (std::string_view name, std::string_view formatPattern, std::string_view filePath, bool replaceIfExists = false) [explicit]
Constructor that will set the logger name, format pattern to use, file path, log directory, and whether or not to truncate this file if it exists or not. Sets all other values to their defaults.
The name of the logger will be set based on the name variable. The format pattern used can be empty if no prepended text is wanted and can include any of, none of, or all of the flags if desired. The file path should include the log directory and the actual file name in the filePath variable as this is how it's intended to be parsed. If the file already exists and the replaceIFExists variable is set to true, then the file will be truncated before opening for use in logging
Parameters
name The name the logger will be identified by.
formatPattern The pattern that is used to determine how the prepended text is displayed before the log message.
filePath The full path to the file. This value should include any directories as well as the file name itself.
replaceIfExist This value denotes whether or not to truncate the file if it exists already
~FileTarget()
serenity::expiremental::targets::FileTarget::~FileTarget ()
Cleans up any background threads, flushes contents to disk, and closes the file context being used.
Cleans up background flush thread if enabled by joining the thread and then flushing the contents of the file handle to the file (if messages were written to buffer, will now write contents of buffer to file). Afterwards, the file context being used is closed.
References CloseFile().
Member Function Documentation
CloseFile()
bool serenity::expiremental::targets::FileTarget::CloseFile ()
Joins any currently running flush background thread (if enabled) and if the file handle's file context is currently open, will flush contents to disk and close the file.
Returns
If successful, returns true. If unsuccessful, will return false with error message
References Flush().
OpenFile()
bool serenity::expiremental::targets::FileTarget::OpenFile (bool truncate = false)
Opens the file held by the file handle.
Opens the file context currently being held and sets the file buffer size using `DEFAULT_BUFFER_SIZE` macro. If the file doessn't already exist, this function will create the file first.
Returns
If successful, returns true. If unsuccessful, will return false with error message
PolicyFlushOn()
void serenity::expiremental::targets::FileTarget::PolicyFlushOn () [override], [protected], [virtual]
Executes the currently set flush policy.
Compares current flush setting and executes that policy if active. Current policies are: always flush, never flush, LogLevel-based flushing and time-based flushing. Time based flushing uses a background thread worker which will intermittenly lock the file when elapsed time is reached from `flushEvery` setting, flush the contents to disk, and then unlock the file for further writes
Reimplemented from serenity::expiremental::targets::TargetBase .
PrintMessage()
void serenity::expiremental::targets::FileTarget::PrintMessage (std::string_view formatted) [override], [protected], [virtual]
Writes the message passed in by the formatted variable to the file context.
Checks if background flush thread is active, if it is - will lock access to the file for writing. If rotate setting is enabled, will check that the file size doesn't exceed file size limit and writes the message to the file. If the file size would exceed the limit, closes the current file and rotates to next file before writing the message. Will then follow any settings active in the flush policy
Parameters
formatted The actual message in its entirety to send to the output destination.
Implements serenity::expiremental::targets::TargetBase .
Reimplemented in serenity::expiremental::targets::RotatingTarget .
RenameFile()
bool serenity::expiremental::targets::FileTarget::RenameFile (std::string_view newFileName) [virtual]
Closes the file (if open) and trys to rename current file context. If rename is succesful, will re-open file context under the new file name.
Virtual function that can be overriden in derived classes. The intended usage is to close the file, try to rename the current file, and then open the file again. This implementation trys to catch any errors in the renaming process and opening process by returning an error message.
Attention
This function, while it doesn't neccessarily throw, does not handle any exceptions that may be thrown when executed. It simply returns an error message to help diagnose issues; error handling is expected to be implemented by the user in this case.
Returns
If successful, returns true. If unsuccessful, will return false with error message
Reimplemented in serenity::expiremental::targets::RotatingTarget .
References CloseFile(), and OpenFile().
The documentation for this class was generated from the following files:
Serenity_Logger/Sandbox/src/Experimental_SB/Targets/FileTarget.h
Serenity_Logger/Sandbox/src/Experimental_SB/Targets/FileTarget.cpp