serenity::expiremental::msg_details::Message_Formatter Class Reference
#include <Message_Formatter.h>
Classes
struct Format_Arg_a
Formatter struct that maps to flag `%a` and represents a padded 12-hour clock's hour value.
struct Format_Arg_A
Formatter struct that maps to flag `%A` and represents the string representation of `AM` or `PM` dependant on the hour.
struct Format_Arg_b
Formatter struct that maps to flag `%b` and represents a padded numerical month value.
struct Format_Arg_B
Formatter struct that maps to flag `%B` and represents the string representation the whole month name (i.e. `January`, `February`, etc..)
struct Format_Arg_Char
Formatter struct that doesn't map to a specific flag and represents any char that that doesn't end up matching with any of the known internal flags.
struct Format_Arg_d
Formatter struct that maps to flag `%d` and represents a padded numerical day value.
struct Format_Arg_D
Formatter struct that maps to flag `%D` and represents the string representation the date in MM/DD/YY format (i.e. 01/29/22)
struct Format_Arg_F
Formatter struct that maps to flag `%F` and represents the string representation the date in YY-MM-DD format.
struct Format_Arg_H
Formatter struct that maps to flag `%H` and represents the string representation of a padded hour on a 24-hour clock.
struct Format_Arg_l
Formatter struct that maps to flag `%l` and represents the one character log level (i.e. `T` for trace, `F` for fatal)
struct Format_Arg_L
Formatter struct that maps to flag `%L` and represents the string representation of the full log level (i.e. `Trace` for trace, `Fatal` for fatal, etc...)
struct Format_Arg_M
Formatter struct that maps to flag `%M` and represents the string representation of a padded minute.
struct Format_Arg_Message
Formatter struct that maps to flag `%+` and represents the formatted message with platform-dependant end of line applied.
struct Format_Arg_n
Formatter struct that maps to flag `%n` and represents the numerical day, textual month, and numerical year in a DDMMMYY format.
struct Format_Arg_N
Formatter struct that maps to flag `%N` and represents the Logger's name to use when formatting.
struct Format_Arg_S
Formatter struct that maps to flag `%S` and represents the string representation of a padded second.
struct Format_Arg_t
Formatter struct that maps to flag `%t` and represents the wall clock time in a 12 hour format (i.e. 12:45:05) format.
struct Format_Arg_T
Formatter struct that maps to flag `%T` and represents the wall clock time in a 24-hour format (i.e. 23:45:05) format.
struct Format_Arg_w
Formatter struct that maps to flag `%w` and represents the unpadded string representation of the numerical weekday value (as in tm_wkday) format.
struct Format_Arg_x
Formatter struct that maps to flag `%x` and represents the string representation of the shortened weekday name (i.e. For Monday - Mon, for Tuesday - Tues, etc...)
struct Format_Arg_X
Formatter struct that maps to flag `%X` and represents the entire Weekday name (i.e. `Monday`, `Tuesday`, etc...) format.
struct Format_Arg_y
Formatter struct that maps to flag `%y` and represents the string representation of the shortened year (i.e. `21`, `22`, etc)
struct Format_Arg_Y
Formatter struct that maps to flag `%Y` and represents the year in YYYY format format.
struct Formatter
Virtual Base Struct that all formatter structs inherit from and implement.
class Formatters
This class is the top-level formatting class that holds and controls each flag arguments specific formatting abilities.
Public Member Functions
 Message_Formatter (std::string_view pattern, Message_Info *details)
Constructor that takes in a format pattern paramater and a Message_Info class pointer.
Message_Formatter (const Message_Formatter &)=delete
 Message_Formatter & operator= (const Message_Info &)=delete
void FlagFormatter (size_t flag)
Intializes and stores the Formatter struct at the index provided into the Formatters container.
void SetPattern (std::string_view pattern)
Sets the format pattern variable and then parses the format string to store each flag as its own individual Formmater struct that will be in charge of how each flag is formatted.
 Formatters & GetFormatters ()
Returns the Message_Formatter's instance of the Formatters container which holds the individual Formatter pointers. Can be called to manually call the Format() function for all arguments stored.
void StoreFormat ()
Store the format pattern internally to be used more efficiently when formatting log messages.
 Message_Info * MessageDetails ()
Returns a pointer to the Message_Info instance used by Message_Formatter.
Public Attributes
 Formatters formatter
std::string fmtPattern
 Message_Info * msgInfo
Detailed Description
Controls how the prepended string of text before the actual log message will be displayed and how each flag/argument is formatted.
Constructor & Destructor Documentation
Message_Formatter()
serenity::expiremental::msg_details::Message_Formatter::Message_Formatter (std::string_view pattern, Message_Info * details) [explicit]
Constructor that takes in a format pattern paramater and a Message_Info class pointer.
The format pattern is set and internally stored by its individual flag arguments to iterate over when a message is logged. The Message_Info class is used to populate the arguments or references when storing and using the individual flag components
References SetPattern().
Member Function Documentation
StoreFormat()
void serenity::expiremental::msg_details::Message_Formatter::StoreFormat ()
Store the format pattern internally to be used more efficiently when formatting log messages.
SetPattern() calls this function internally. Parses the internal format pattern string stored from SetPattern() or from a constructor that took in a format pattern argument and for each flag found by the delimiter `%`, will try to match the potential flag to the index of the valid flags array. If a match is found, initializes and stores the respective Formatter struct for that flag, otherwise, stores this value as well as any other char, by passing in the value to initialize and store a Format_Arg_Char struct instead
References serenity::expiremental::msg_details::Message_Formatter::Formatters::Clear(), serenity::expiremental::msg_details::Message_Formatter::Formatters::Emplace_Back(), and FlagFormatter().
The documentation for this class was generated from the following files:
Serenity_Logger/Sandbox/src/Experimental_SB/MessageDetails/Message_Formatter.h
Serenity_Logger/Sandbox/src/Experimental_SB/MessageDetails/Message_Formatter.cpp