serenity::expiremental::targets::ColorConsole Class Reference
This class is in charge of logging to the terminal and supports color logging and the ability to log without color. This class inherits from the TargetBase class for common logging functions and logging settings.
#include <ColorConsoleTarget.h>
Public Member Functions
ColorConsole ()
Default constructor that will set the logger name to `Console_Logger`. All other settings to their defaults.
 ColorConsole (std::string_view name)
Constructor that will set the logger name to the parameter name passed in. All other settings to their defaults.
 ColorConsole (std::string_view name, std::string_view msgPattern)
Constructor that will set the logger name to the parameter name passed in and set the format pattern via the parameter msgPattern passed in. All other settings to their defaults.
 ~ColorConsole ()
If the output wasn't directed to a terminal, will flush the contents.
std::string_view GetMsgColor (LoggerLevel level)
Returns the log level based color for the current message to use.
void SetMsgColor (LoggerLevel level, std::string_view color)
Sets color specified for the log level specified.
void SetConsoleInterface (console_interface mode)
Sets console mode. Console modes mirror standard outputs.
const console_interface ConsoleInterface ()
Returns the current console mode being used.
void ColorizeOutput (bool colorize)
Enables/Disables colored text output.
void SetOriginalColors ()
Initializes the default colors to use for log levels.
bool IsTerminalType ()
Checks to see if output handle is referring to a terminal type device or not.
bool IsValidHandle ()
Checks to see if output handle is valid and not empty.
void PrintMessage (std::string_view formatted) override
Outputs the message (formatted) to the destination output device.
Additional Inherited Members
Detailed Description
This class is in charge of logging to the terminal and supports color logging and the ability to log without color. This class inherits from the TargetBase class for common logging functions and logging settings.
For all Console Target Constructors:
will set the console mode to `console_interface::stdout`
Initializes the default colors to use for each message level
If output is a terminal and hasn't been redirected and if the output handle is valid, enables color output
Sets `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag if on Windows Platform
Constructor & Destructor Documentation
ColorConsole() [1/2]
serenity::expiremental::targets::ColorConsole::ColorConsole (std::string_view name) [explicit]
Constructor that will set the logger name to the parameter name passed in. All other settings to their defaults.
Parameters
name the name that the logger itself will use and be identified by
References IsTerminalType(), IsValidHandle(), SetConsoleInterface(), SetOriginalColors(), and serenity::expiremental::targets::TargetBase::WriteToBaseBuffer().
ColorConsole() [2/2]
serenity::expiremental::targets::ColorConsole::ColorConsole (std::string_view name, std::string_view msgPattern) [explicit]
Constructor that will set the logger name to the parameter name passed in and set the format pattern via the parameter msgPattern passed in. All other settings to their defaults.
Parameters
name the name that the logger itself will use and be identified by
msgPattern the format pattern that determines how the prepended text will be displayed before the log message
References IsTerminalType(), IsValidHandle(), SetConsoleInterface(), SetOriginalColors(), and serenity::expiremental::targets::TargetBase::WriteToBaseBuffer().
~ColorConsole()
serenity::expiremental::targets::ColorConsole::~ColorConsole ()
If the output wasn't directed to a terminal, will flush the contents.
If on Windows platform, this function will also reset the console mode to default in order to to clear `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag.
References IsTerminalType().
Member Function Documentation
GetMsgColor()
std::string_view serenity::expiremental::targets::ColorConsole::GetMsgColor (LoggerLevel level)
Returns the log level based color for the current message to use.
Parameters
level the level used to recieve the color code for that level. Logger levels are trace, info, debug, warning, error, and fatal.
Returns
The ansi color code for the level passed in
PrintMessage()
void serenity::expiremental::targets::ColorConsole::PrintMessage (std::string_view formatted) [override], [virtual]
Outputs the message (formatted) to the destination output device.
If output handle is valid, will write the message to the output. If color is enabled, will write the message in the color specified for the log level used if the output is to a terminal. For windows, uses WriteConsole() unless the output is not a terminal (in which case, uses WriteFile())
Parameters
formatted The actual message in its entirety to send to the output destination.
Implements serenity::expiremental::targets::TargetBase .
References IsTerminalType(), IsValidHandle(), and serenity::expiremental::targets::TargetBase::MsgInfo().
SetConsoleInterface()
void serenity::expiremental::targets::ColorConsole::SetConsoleInterface (console_interface mode)
Sets console mode. Console modes mirror standard outputs.
For Windows, sets `ENABLE_VIRTUAL_TERMINAL_PROCESSING`. (If not defined, a macro is used to define this value). For any other platfrom, sets the standard output to use. The console_interface values (std_out, std_err, std_log) represent std::out, std::err, and std::clog respectively.
Parameters
mode Can be one of the following: console_interface::std_out, console_interface::std_err, or console_interface::std_log
SetMsgColor()
void serenity::expiremental::targets::ColorConsole::SetMsgColor (LoggerLevel level, std::string_view color)
Sets color specified for the log level specified.
Parameters
level The logger level to bind the color code to from @color
color The color code to bind to the level passed in. This color code is expected to be an ansi code.
The documentation for this class was generated from the following files:
Serenity_Logger/Sandbox/src/Experimental_SB/Targets/ColorConsoleTarget.h
Serenity_Logger/Sandbox/src/Experimental_SB/Targets/ColorConsoleTarget.cpp