.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_F" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_F \- \fBFormatter\fP struct that maps to flag '%F' and represents the string representation the date in YY-MM-DD format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_F\fP (\fBMessage_Info\fP &info)"
.br
.RI "Constructor that uses the \fBMessage_Info\fP pointer to store a reference to the cache and intitialize the current and last known day values\&. "
.ti -1c
.RI "std::string \fBUpdateInternalView\fP () override"
.br
.RI "Will update the last known day to the current day and then return a string representation of the date in YY-MM-DD format\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns The Formatted Argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that maps to flag '%F' and represents the string representation the date in YY-MM-DD format\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_F::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns The Formatted Argument\&. When called, if the current day value doesn't match the last known day value, will update the last known day value to the current day value and then call \fBUpdateInternalView( )\fP to update the internal string representation of the current date in YY-MM-DD format, otherwise, just returns the internal date representation stored 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "std::string serenity::expiremental::msg_details::Message_Formatter::Format_Arg_F::UpdateInternalView ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Will update the last known day to the current day and then return a string representation of the date in YY-MM-DD format\&. 
.PP
Reimplemented from \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
