.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_Char" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_Char \- \fBFormatter\fP struct that doesn't map to a specific flag and represents any char that that doesn't end up matching with any of the known internal flags\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_Char\fP (std::string_view ch)"
.br
.RI "Constructor that takes a string_view argument to store for later use in appending formatting arguments\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns the stored representation of the value passed in during construction\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that doesn't map to a specific flag and represents any char that that doesn't end up matching with any of the known internal flags\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_Char::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns the stored representation of the value passed in during construction\&. 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
