.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_M" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_M \- \fBFormatter\fP struct that maps to flag '%M' and represents the string representation of a padded minute\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_M\fP (\fBMessage_Info\fP &info)"
.br
.RI "Constructor that uses the \fBMessage_Info\fP pointer to store a reference to the cache and intitialize the current and last known minute values\&. "
.ti -1c
.RI "std::string \fBUpdateInternalView\fP () override"
.br
.RI "Will update the last known minute to the current minute and then return a string representation of the padded minute value\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns The Formatted Argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that maps to flag '%M' and represents the string representation of a padded minute\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_M::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns The Formatted Argument\&. When called, if the current minute value doesn't match the last known minute value, will update the last known minute value to the current minute value and then call \fBUpdateInternalView( )\fP to update the internal string representation of the current padded minute, otherwise, just returns the internal padded minute value stored 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "std::string serenity::expiremental::msg_details::Message_Formatter::Format_Arg_M::UpdateInternalView ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Will update the last known minute to the current minute and then return a string representation of the padded minute value\&. 
.PP
Reimplemented from \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
