.TH "serenity::expiremental::msg_details::Message_Info" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Info
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessage_Info\fP (std::string_view name, LoggerLevel level, message_time_mode mode)"
.br
.ti -1c
.RI "\fBMessage_Info\fP & \fBoperator=\fP (const \fBMessage_Info\fP &t)=delete"
.br
.ti -1c
.RI "\fBMessage_Info\fP (const \fBMessage_Info\fP &)=delete"
.br
.ti -1c
.RI "std::string & \fBMessageBuffer\fP ()"
.br
.ti -1c
.RI "LoggerLevel & \fBMsgLevel\fP ()"
.br
.ti -1c
.RI "std::string & \fBName\fP ()"
.br
.ti -1c
.RI "\fBMessage_Time\fP & \fBTimeDetails\fP ()"
.br
.ti -1c
.RI "void \fBSetName\fP (const std::string_view name)"
.br
.ti -1c
.RI "void \fBSetMsgLevel\fP (const LoggerLevel level)"
.br
.ti -1c
.RI "std::chrono::system_clock::time_point \fBMessageTimePoint\fP ()"
.br
.ti -1c
.RI "void \fBSetTimeMode\fP (const message_time_mode mode)"
.br
.ti -1c
.RI "message_time_mode \fBTimeMode\fP ()"
.br
.ti -1c
.RI "std::tm & \fBTimeInfo\fP ()"
.br
.ti -1c
.RI "std::string & \fBMessage\fP ()"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBSetMessage\fP (const std::string_view message, Args &&\&.\&.\&.args)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
