.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_T" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_T \- \fBFormatter\fP struct that maps to flag '%T' and represents the wall clock time in a 24-hour format (i\&.e\&. 23:45:05) format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_T\fP (\fBMessage_Info\fP &info)"
.br
.RI "Constructor that uses the \fBMessage_Info\fP pointer to store a reference to the cache and intitialize the current and last known minute values\&. "
.ti -1c
.RI "std::string \fBUpdateInternalView\fP () override"
.br
.RI "Will update the last known minute to the current minute and then return a string representation of the wall clock time in a 24-hour format\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns The Formatted Argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that maps to flag '%T' and represents the wall clock time in a 24-hour format (i\&.e\&. 23:45:05) format\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_T::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns The Formatted Argument\&. When called, if the current minute doesn't match the last known minute, will update the last known minute to the current minute and then call \fBUpdateInternalView( )\fP to update the internal string representation of the time in a 24-hour format, otherwise, just returns the internal string representation of the time in a 24-hour format stored 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "std::string serenity::expiremental::msg_details::Message_Formatter::Format_Arg_T::UpdateInternalView ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Will update the last known minute to the current minute and then return a string representation of the wall clock time in a 24-hour format\&. 
.PP
Reimplemented from \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
