.TH "serenity::expiremental::targets::TargetBase" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::targets::TargetBase \- The base class that derived target classes inherit from\&. Contains common functions between all targets for message logging and logging settings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Target\&.h>\fP
.PP
Inherited by \fBserenity::expiremental::targets::ColorConsole\fP, and \fBserenity::expiremental::targets::FileTarget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTargetBase\fP ()"
.br
.RI "Default constructor that sets the logger name to 'Base_Target' and sets all other values to their defaults\&. "
.ti -1c
.RI "\fBTargetBase\fP (std::string_view name)"
.br
.ti -1c
.RI "\fBTargetBase\fP (std::string_view name, std::string_view msgPattern)"
.br
.ti -1c
.RI "void \fBSetFlushPolicy\fP (\fBFlush_Policy\fP pPolicy)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP & \fBPolicy\fP ()"
.br
.RI "Returns the current policy in use\&. "
.ti -1c
.RI "const std::string \fBLoggerName\fP ()"
.br
.RI "Returns the logger's name\&. "
.ti -1c
.RI "void \fBSetPattern\fP (std::string_view pattern)"
.br
.RI "Calls the handle to the Message_Formatter's \fBSetPattern( )\fP function\&. "
.ti -1c
.RI "void \fBResetPatternToDefault\fP ()"
.br
.RI "Resets the current format pattern in use to the default format pattern\&. "
.ti -1c
.RI "void \fBSetLogLevel\fP (LoggerLevel level)"
.br
.RI "Sets the log level that messages should be logged at\&. "
.ti -1c
.RI "void \fBWriteToBaseBuffer\fP (bool fmtToBuf=true)"
.br
.RI "Enables/Disables writing to a buffer\&. "
.ti -1c
.RI "bool \fBisWriteToBuf\fP ()"
.br
.RI "Returns true if buffer writes are enabled and false if they are disabled\&. "
.ti -1c
.RI "std::string * \fBBuffer\fP ()"
.br
.RI "Returns the buffer container\&. "
.ti -1c
.RI "const LoggerLevel \fBLevel\fP ()"
.br
.RI "Returns the current log level setting (the threshold of whether to log a message or not)\&. "
.ti -1c
.RI "void \fBSetLoggerName\fP (std::string_view name)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBTrace\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::trace setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBInfo\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::info setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBDebug\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::debug setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBWarn\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::warning setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBError\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::error setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBFatal\fP (std::string_view msg, Args &&\&.\&.\&.args)"
.br
.RI "Logs a message giving the message a LoggerLevel::fatal setting\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBTrace\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBInfo\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBDebug\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBWarn\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBError\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBFatal\fP (std::string_view s, Args &&\&.\&.\&.args)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPrintMessage\fP (std::string_view formatted)=0"
.br
.RI "Pure virtual function that all derived classes must implement and is used to write the formatted message to a specific target\&. "
.ti -1c
.RI "virtual void \fBPolicyFlushOn\fP ()"
.br
.ti -1c
.RI "\fBmsg_details::Message_Formatter\fP * \fBMsgFmt\fP ()"
.br
.RI "Returns a pointer to the handle for the Message_Formatter class instance\&. "
.ti -1c
.RI "\fBmsg_details::Message_Info\fP * \fBMsgInfo\fP ()"
.br
.RI "Returns a pointer to the handle for the Message_Info class instance\&. "
.in -1c
.SH "Detailed Description"
.PP 
The base class that derived target classes inherit from\&. Contains common functions between all targets for message logging and logging settings\&. 

For All \fBTargetBase\fP Constructors: 
.br
The following default values are set regardless of which constructor is used: 
.br
.IP "\(bu" 2
Flush Policy is set to 'never'\&. 
.br

.IP "\(bu" 2
Log Level is set to 'LoggerLevel::trace'\&. 
.br

.IP "\(bu" 2
Default pattern is set to '|%l| %x %n %T [%N]: %+' which translates to the form of: 
.br
 '|T| Sat 29Jan22 [Base_Logger]: The message to log'\&. 
.br

.IP "\(bu" 2
Time mode used is set to 'time_mode::local'\&.
.br
 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "serenity::expiremental::targets::TargetBase::TargetBase (std::string_view name)"
Constructor that will set the logger name to the name paramater passed in and all other values to their defaults\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP the name that the logger itself will use and be identified by 
.RE
.PP

.SS "serenity::expiremental::targets::TargetBase::TargetBase (std::string_view name, std::string_view msgPattern)"
Constructor that will set the logger name to the name paramater passed in as well as the format pattern to the msgPattern passed in\&. All other values will be assigned their default values\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP the name that the logger itself will use and be identified by 
.br
\fImsgPattern\fP the format pattern that determines how the prepended text will be displayed before the log message 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Debug (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::debug setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Error (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::error setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Fatal (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::fatal setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Info (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::info setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "virtual void serenity::expiremental::targets::TargetBase::PolicyFlushOn ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"
Virtual function that can be omitted if derived class has no need to implement and is used to handle how and when the derived target should flush its contents to disk\&. 
.PP
Reimplemented in \fBserenity::expiremental::targets::FileTarget\fP\&.
.SS "virtual void serenity::expiremental::targets::TargetBase::PrintMessage (std::string_view formatted)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Pure virtual function that all derived classes must implement and is used to write the formatted message to a specific target\&. 
.PP
\fBParameters\fP
.RS 4
\fIformatted\fP The actual message in its entirety to send to the output destination\&.
.RE
.PP
For built in targets, the message is formatted before reaching this point by calling Message_Info's SetMessage( ) function\&. \fBPrintMessage( )\fP's intended usage is the last stop call before a log message is sent to its destination 
.PP
Implemented in \fBserenity::expiremental::targets::ColorConsole\fP, \fBserenity::expiremental::targets::FileTarget\fP, and \fBserenity::expiremental::targets::RotatingTarget\fP\&.
.SS "void serenity::expiremental::targets::TargetBase::SetFlushPolicy (\fBFlush_Policy\fP pPolicy)"
Sets the current policy in use to defer to the policy passed in from 'pPolicy'\&. 
.PP
\fBParameters\fP
.RS 4
\fIpPolicy\fP refers to any settings that are added or changed by the user, including whether to flush always, never, or periodically\&.
.RE
.PP
On top of having options to never flush, always flush, and periodically flush, the \fBFlush_Policy\fP class includes the settings for whether flushing should occur based on a time-interval or log level if the periodical flushing option is enabled\&. 
.SS "void serenity::expiremental::targets::TargetBase::SetLoggerName (std::string_view name)"
Sets the name of the logger 
.PP
\fBParameters\fP
.RS 4
\fIname\fP the name that the logger itself will use and be identified by 
.RE
.PP

.SS "void serenity::expiremental::targets::TargetBase::SetLogLevel (LoggerLevel level)"

.PP
Sets the log level that messages should be logged at\&. For example, if 'SetLogLevel(LoggerLevel::Error);' is used, then no messages below LoggerLevel::Error will be logged, however once a Fatal or Error message is made, then they would be logged to the output destination 
.PP
\fBParameters\fP
.RS 4
\fIlevel\fP - the logger level threshold that will determine if a message should be logged or not 
.RE
.PP

.SS "void serenity::expiremental::targets::TargetBase::SetPattern (std::string_view pattern)"

.PP
Calls the handle to the Message_Formatter's \fBSetPattern( )\fP function\&. Sets the format pattern variable and parses the format string for internal storage and usage of this pattern by initializing and moving the initialized formatter struct in charge of the respective flag to a Formatters container 
.PP
\fBParameters\fP
.RS 4
\fIpattern\fP - the format pattern to store\&. This pattern is what determines how the prepended text will be displayed before the log message 
.RE
.PP

.PP
References \fBserenity::expiremental::msg_details::Message_Formatter::SetPattern()\fP\&.
.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Trace (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::trace setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. Args> void serenity::expiremental::targets::TargetBase::Warn (std::string_view msg, Args &&\&.\&.\&. args)"

.PP
Logs a message giving the message a LoggerLevel::warning setting\&. Checks if the message should be logged via the log level threshold setting\&. If it isn't, immediately returns\&. If the message should be logged, this function will then perform a quick check on whether or not writes to the buffer were enabled and will write to the buffer if they were\&. If writes to the buffers weren't enabled, then \fBPrintMessage( )\fP will be called and the derived target handles how this is implemented\&. After writing the message, follows the derived target's \fBPolicyFlushOn( )\fP implementation 
.PP
\fBTemplate Parameters\fP
.RS 4
\fImsg\fP The message being passed in\&. Follows C++20's format library and libfmt's substitution model using '{}' to replace any arguments from the \fCargs\fP parameter\&. 
.br
\fIargs\fP Variadic placeholder for any number of and any type of arguments to use in substituion\&. 
.RE
.PP

.SS "void serenity::expiremental::targets::TargetBase::WriteToBaseBuffer (bool fmtToBuf = \fCtrue\fP)"

.PP
Enables/Disables writing to a buffer\&. When writing to the buffer, messages will be appended with the platform-specific end of line before being added to the buffer\&. When Flush( ) is called, if writing to the buffer was enabled, the buffer contents will now be written to the file and then flushed to disk\&. Disabled by default\&. 
.PP
\fBParameters\fP
.RS 4
\fIfmtToBuf\fP the value that controls whether or not buffer writes are enabled/disabled 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
