.TH "serenity::expiremental::BackgroundThread" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::BackgroundThread
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::atomic< bool > \fBcleanUpThreads\fP { false }"
.br
.ti -1c
.RI "std::atomic< bool > \fBflushThreadEnabled\fP { false }"
.br
.ti -1c
.RI "std::mutex \fBreadWriteMutex\fP"
.br
.ti -1c
.RI "std::thread \fBflushThread\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
