.TH "serenity::expiremental::msg_details::Message_Formatter::Formatters" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Formatters \- This class is the top-level formatting class that holds and controls each flag arguments specific formatting abilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormatters\fP (std::vector< std::unique_ptr< \fBFormatter\fP > > &&container)"
.br
.RI "Constructor that takes ownership of the vector of \fBFormatter\fP pointers passed in\&. "
.ti -1c
.RI "\fBFormatters\fP ()=default"
.br
.RI "Default Constructor\&. "
.ti -1c
.RI "void \fBEmplace_Back\fP (std::unique_ptr< \fBFormatter\fP > &&formatter)"
.br
.RI "Takes ownership of the \fBFormatter\fP pointer passed in and stores this pointer in the internal \fBFormatters\fP container\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP ()"
.br
.RI "Calls each \fBFormatter\fP pointer's specific \fBFormat()\fP implementation that is stored in the internal \fBFormatter\fP container in the order they are stored and returns the whole formatted string as a view\&. "
.ti -1c
.RI "void \fBClear\fP ()"
.br
.RI "Clears the internal \fBFormatter\fP pointers container\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class is the top-level formatting class that holds and controls each flag arguments specific formatting abilities\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
