.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_w" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_w \- \fBFormatter\fP struct that maps to flag '%w' and represents the unpadded string representation of the numerical weekday value (as in tm_wkday) format\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_w\fP (\fBMessage_Info\fP &info)"
.br
.RI "Constructor that uses the \fBMessage_Info\fP pointer to store a reference to the cache and intitialize the current and last known numerical weekday values\&. "
.ti -1c
.RI "std::string \fBUpdateInternalView\fP () override"
.br
.RI "Will update the last known numerical weekday to the current numerical weekday and then return an unpadded string representation of the numerical weekday\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns The Formatted Argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that maps to flag '%w' and represents the unpadded string representation of the numerical weekday value (as in tm_wkday) format\&. 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_w::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns The Formatted Argument\&. When called, if the current numerical weekday value doesn't match the last known numerical weekday value, will update the last known numerical weekday value to the current numerical weekday value and then call \fBUpdateInternalView( )\fP to update the internal string representation of the new weekday value, otherwise, just returns the internal numerical weekday representation stored 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "std::string serenity::expiremental::msg_details::Message_Formatter::Format_Arg_w::UpdateInternalView ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Will update the last known numerical weekday to the current numerical weekday and then return an unpadded string representation of the numerical weekday\&. 
.PP
Reimplemented from \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
