.TH "serenity::expiremental::PeriodicSettings" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::PeriodicSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::chrono::milliseconds \fBflushEvery\fP { std::chrono::milliseconds( 500 ) }"
.br
.ti -1c
.RI "LoggerLevel \fBflushOn\fP { LoggerLevel::trace }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
