.TH "serenity::expiremental::msg_details::Message_Formatter::Format_Arg_L" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::msg_details::Message_Formatter::Format_Arg_L \- \fBFormatter\fP struct that maps to flag '%L' and represents the string representation of the full log level (i\&.e\&. 'Trace' for trace, 'Fatal' for fatal, etc\&.\&.\&.)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Message_Formatter\&.h>\fP
.PP
Inherits \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormat_Arg_L\fP (\fBMessage_Info\fP &info)"
.br
.RI "Constructor that uses the \fBMessage_Info\fP pointer to store a reference to the message level\&. "
.ti -1c
.RI "std::string \fBUpdateInternalView\fP () override"
.br
.RI "Will update the last known level to the current level and return the string representation of the log level\&. "
.ti -1c
.RI "std::string_view \fBFormat\fP () override"
.br
.RI "Returns The Formatted Argument\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBFormatter\fP struct that maps to flag '%L' and represents the string representation of the full log level (i\&.e\&. 'Trace' for trace, 'Fatal' for fatal, etc\&.\&.\&.) 
.SH "Member Function Documentation"
.PP 
.SS "std::string_view serenity::expiremental::msg_details::Message_Formatter::Format_Arg_L::Format ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Returns The Formatted Argument\&. When called, if the current log level doesn't match the last level seen, will update the last known level variable as well as the internal representation of the level string and return the internal representation, otherwise, just returns the internal representation of the level string stored 
.PP
Implements \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.
.SS "std::string serenity::expiremental::msg_details::Message_Formatter::Format_Arg_L::UpdateInternalView ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Will update the last known level to the current level and return the string representation of the log level\&. 
.PP
Reimplemented from \fBserenity::expiremental::msg_details::Message_Formatter::Formatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
