.TH "serenity::expiremental::FileSettings" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::FileSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::filesystem::path \fBfilePath\fP"
.br
.ti -1c
.RI "std::vector< char > \fBfileBuffer\fP"
.br
.ti -1c
.RI "size_t \fBbufferSize\fP { DEFAULT_BUFFER_SIZE }"
.br
.ti -1c
.RI "size_t \fBfileBufOccupied\fP { 0 }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
