.TH "serenity::expiremental::RotateSettings" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::RotateSettings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetOriginalSettings\fP (const std::filesystem::path &filePath)"
.br
.ti -1c
.RI "void \fBSetCurrentFileSize\fP (size_t currentSize)"
.br
.ti -1c
.RI "const std::filesystem::path & \fBOriginalPath\fP ()"
.br
.ti -1c
.RI "const std::filesystem::path & \fBOriginalDirectory\fP ()"
.br
.ti -1c
.RI "const std::string & \fBOriginalName\fP ()"
.br
.ti -1c
.RI "const std::string & \fBOriginalExtension\fP ()"
.br
.ti -1c
.RI "const size_t & \fBFileSize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrotateOnFileSize\fP { true }"
.br
.ti -1c
.RI "size_t \fBmaxNumberOfFiles\fP { 5 }"
.br
.ti -1c
.RI "size_t \fBfileSizeLimit\fP { 512 * KB }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
