.TH "serenity::expiremental::Flush_Policy" 3 "Mon Jan 31 2022" "Serenity Logger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
serenity::expiremental::Flush_Policy
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFlush_Policy\fP (Flush primaryOpt)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP (Flush primaryOpt, PeriodicOptions secondaryOpt, \fBPeriodicSettings\fP settings)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP (Flush primaryOpt, PeriodicOptions secondaryOpt)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP (PeriodicOptions secondaryOpt, \fBPeriodicSettings\fP settings)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP (const \fBFlush_Policy\fP &p)"
.br
.ti -1c
.RI "\fBFlush_Policy\fP & \fBoperator=\fP (const \fBFlush_Policy\fP &p)"
.br
.ti -1c
.RI "void \fBSetPrimaryMode\fP (Flush primary)"
.br
.ti -1c
.RI "void \fBSetSecondaryMode\fP (PeriodicOptions secondary)"
.br
.ti -1c
.RI "void \fBSetSecondarySettings\fP (\fBPeriodicSettings\fP subSettings)"
.br
.ti -1c
.RI "const Flush \fBPrimarySetting\fP ()"
.br
.ti -1c
.RI "const PeriodicOptions \fBSubSetting\fP ()"
.br
.ti -1c
.RI "const \fBFlush_Policy\fP \fBPolicy\fP ()"
.br
.ti -1c
.RI "const \fBPeriodicSettings\fP \fBSecondarySettings\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Serenity Logger from the source code\&.
